
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: death-star.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker:
  - platform: huawei_router
    host: 192.168.1.1
    username: vodafone
    password: RuaDiu612
lovelace:
  mode: yaml

google_assistant:
  project_id: home-assistant-277315
  service_account: !include Home Assistant-b640ced71d95.json
  report_state: true
  exposed_domains:
    - switch
    - light

sonoff:
  username: graemejallen83@gmail.com
  password: DeathStar
  scan_interval: 60 #(optional, lower values than 60 won't work anymore!)
  grace_period: 600 #(optional)
  api_region: 'eu' #(optional)
  entity_prefix: True #(optional)
  debug: false #(optional)
  
# DUMMY DEVICES #

input_boolean:
  living_room_blinds:
    name: Living Room Blinds
  kitchen_blinds:
    name: Kitchen Blinds    
    
input_number:
  daylight_tester:
    name: brightness
    initial: 100
    min: 0
    max: 100
    step: 1